<a href="https://colab.research.google.com/github/cateto/python4NLP/blob/main/ml_lec/file_input.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload() 

Saving data-01-test-score.csv to data-01-test-score.csv


In [2]:
import numpy as np
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

In [3]:
x_data = xy[:, 0:-1] # 전체 행은 다 가져오고 열은 마지막 1개 제외
y_data = xy[:, [-1]] # 전체 행은 다 가져오고 마지막 1개만 가져오겠다.


In [4]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [7]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

Instructions for updating:
non-resource variables are not supported in the long term


In [8]:
W = tf.Variable(tf.random_normal([3,1]), name='weight') # 들어오는값 , 나가는 값
b = tf.Variable(tf.random_normal([1]), name='bias') # 나가는 값

In [9]:
hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [12]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y:y_data})
  if step % 10 == 0:
    print(step, "Cost: " ,cost_val, "\n Prediction:\n", hy_val)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [174.6926 ]
 [174.03242]
 [166.3433 ]
 [153.72345]
 [191.70093]]
160 Cost:  9.023796 
 Prediction:
 [[153.30351 ]
 [185.23225 ]
 [182.0525  ]
 [198.71661 ]
 [140.96663 ]
 [104.384674]
 [148.86882 ]
 [110.586105]
 [173.7039  ]
 [161.73105 ]
 [143.25415 ]
 [141.74074 ]
 [187.74345 ]
 [155.44974 ]
 [149.71921 ]
 [188.26137 ]
 [147.80276 ]
 [178.87083 ]
 [178.76396 ]
 [159.84485 ]
 [174.6975  ]
 [174.03542 ]
 [166.3466  ]
 [153.7113  ]
 [191.69827 ]]
170 Cost:  9.001711 
 Prediction:
 [[153.2999 ]
 [185.23193]
 [182.0498 ]
 [198.7173 ]
 [140.9644 ]
 [104.38908]
 [148.87358]
 [110.59544]
 [173.70894]
 [161.74406]
 [143.25623]
 [141.74594]
 [187.73705]
 [155.4395 ]
 [149.72499]
 [188.2641 ]
 [147.78989]
 [178.8779 ]
 [178.75665]
 [159.83853]
 [174.70236]
 [174.03838]
 [166.34988]
 [153.6992 ]
 [191.69559]]
180 Cost:  8.979785 
 Prediction:
 [[153.29631]
 [185.2316 ]
 [182.04713]
 [198.71797]
 [140.96219]
 [104.39344]
 [148.87833]
 [110.60475]
 [173.71396]

In [13]:
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

Your score will be  [[186.998]]


In [14]:
print("Other's scores will be", sess.run(hypothesis, feed_dict={X:[[60, 70, 110], [90, 100, 80]]}))

Other's scores will be [[174.69598]
 [177.32825]]


## Queue Runners 
:파일 여러개 업로드하여 사용

1. file list 만듦
2. file 리더 연결
3. file 형태 정의
4. 디코딩

In [16]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [17]:
sess =tf.Session()

In [18]:
# 파일 이름 큐를 축적
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess,coord=coord)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [19]:
for step in range(2001):
  x_batch, y_batch = sess.run([train_x_batch, train_y_batch])

In [20]:
coord.request_stop()
coord.join(threads)

구현


In [21]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue'
)

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [22]:
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [25]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [26]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3,1]), name='weight') # 들어오는값 , 나가는 값
b = tf.Variable(tf.random_normal([1]), name='bias') # 나가는 값

hypothesis = tf.matmul(X, W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [27]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
  x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X : x_batch, Y: y_batch})

  if step % 10 == 0:
    print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 68.96849 
Prediction:
 [[154.22676]
 [178.8342 ]
 [179.7563 ]
 [193.74783]
 [136.39813]
 [ 96.60948]
 [143.80089]
 [105.10066]
 [163.11264]
 [145.98381]]
10 Cost: 37.960766 
Prediction:
 [[157.96657]
 [183.36812]
 [184.20236]
 [198.6044 ]
 [139.85374]
 [ 99.18404]
 [147.44675]
 [107.81711]
 [167.37663]
 [149.96877]]
20 Cost: 37.523094 
Prediction:
 [[157.96893]
 [183.40906]
 [184.22191]
 [198.63992]
 [139.88268]
 [ 99.23181]
 [147.48386]
 [107.85817]
 [167.44116]
 [150.06343]]
30 Cost: 37.192223 
Prediction:
 [[157.9462 ]
 [183.41962]
 [184.21161]
 [198.6429 ]
 [139.88846]
 [ 99.2624 ]
 [147.49657]
 [107.88111]
 [167.47716]
 [150.13152]]
40 Cost: 36.865215 
Prediction:
 [[157.92339 ]
 [183.42993 ]
 [184.20117 ]
 [198.64566 ]
 [139.89401 ]
 [ 99.29271 ]
 [147.50903 ]
 [107.903824]
 [167.51279 ]
 [150.19913 ]]
50 Cost: 36.54139 
Prediction:
 [[157.90068]
 [183.44016]
 [184.19077]
 [198.64839]
 [139.89955]
 [ 99.32288]
 [147.52147]
 [107.92644]
 [167.54825]
 [150.2664 ]]
60 Cost: 

In [28]:
coord.request_stop()
coord.join(threads)