<a href="https://colab.research.google.com/github/cateto/python4NLP/blob/main/ml-lec/multi_variable_linear_reg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Lab 4 Multi-variable linear regression
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.set_random_seed(777)  # for reproducibility

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


Instructions for updating:
non-resource variables are not supported in the long term
0 Cost:  77437.836 
Prediction:
 [ -99.19784 -109.40472 -112.99919 -123.97137  -79.7757 ]
10 Cost:  10.199746 
Prediction:
 [146.96669 186.4446  178.51767 193.48209 145.8782 ]
20 Cost:  9.441347 
Prediction:
 [147.72311 187.33174 179.40324 194.44539 146.55028]
30 Cost:  9.392073 
Prediction:
 [147.737   187.32648 179.40944 194.45108 146.54167]
40 Cost:  9.343043 
Prediction:
 [147.74861 187.31851 179.41296 194.45387 146.53104]
50 Cost:  9.294317 
Prediction:
 [147.76016 187.31058 179.41647 194.45665 146.52042]
60 Cost:  9.245825 
Prediction:
 [147.77168 187.30264 179.41997 194.4594  146.50981]
70 Cost:  9.197584 
Prediction:
 [147.78317 187.29472 179.42346 194.46214 146.49924]
80 Cost:  9.149622 
Prediction:
 [147.79466 187.28687 179.42696 194.46492 146.48872]
90 Cost:  9.101915 
Prediction:
 [147.80608 187.27899 179.43044 194.46764 146.4782 ]
100 Cost:  9.054459 
Prediction:
 [147.81749 187.27113 179.

In [3]:
# Lab 4 Multi-variable linear regression
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
tf.set_random_seed(777)  # for reproducibility

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  105818.29 
Prediction:
 [[-133.5243 ]
 [-164.79396]
 [-160.21033]
 [-174.73904]
 [-126.3673 ]]
10 Cost:  8.311992 
Prediction:
 [[154.21866]
 [181.07106]
 [180.56628]
 [196.35913]
 [137.44464]]
20 Cost:  7.304976 
Prediction:
 [[155.07901]
 [182.12457]
 [181.59424]
 [197.47952]
 [138.25221]]
30 Cost:  7.266832 
Prediction:
 [[155.07141]
 [182.13478]
 [181.59424]
 [197.4805 ]
 [138.264  ]]
40 Cost:  7.2288847 
Prediction:
 [[155.0612 ]
 [182.14182]
 [181.59114]
 [197.4781 ]
 [138.27338]]
50 Cost:  7.1911535 
Prediction:
 [[155.05101]
 [182.14882]
 [181.58804]
 [197.4757 ]
 [138.2827 ]]
60 Cost:  7.153601 
Prediction:
 [[155.04085]
 [182.1558 ]
 [181.58495]
 [197.47328]
 [138.292  ]]
70 Cost:  7.1162896 
Prediction:
 [[155.0307 ]
 [182.16277]
 [181.58185]
 [197.4709 ]
 [138.30127]]
80 Cost:  7.0791917 
Prediction:
 [[155.0206 ]
 [182.1697 ]
 [181.57877]
 [197.4685 ]
 [138.31052]]
90 Cost:  7.0422525 
Prediction:
 [[155.01053]
 [182.17665]
 [181.57573]
 [197.46616]
 [138.31976]]
