<a href="https://colab.research.google.com/github/cateto/python4NLP/blob/main/colab/intro_datastructure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install pandas

In [4]:
import pandas as pd
sr = pd.Series([17000, 18000, 1000, 5000], index=["피자", "치킨", "콜라", "맥주"])
print(sr)

피자    17000
치킨    18000
콜라     1000
맥주     5000
dtype: int64


In [5]:
print(sr.values)

[17000 18000  1000  5000]


In [6]:
print(sr.index)

Index(['피자', '치킨', '콜라', '맥주'], dtype='object')


In [8]:
values = [[1,2,3], [4,5,6], [7,8,9]]
index = ['i1', 'i2', 'i3']
columns = ['A', 'B', 'C']
df = pd.DataFrame(values, index=index, columns=columns)
print(df)

    A  B  C
i1  1  2  3
i2  4  5  6
i3  7  8  9


In [9]:
print(df.index)

Index(['i1', 'i2', 'i3'], dtype='object')


In [10]:
print(df.columns)

Index(['A', 'B', 'C'], dtype='object')


In [11]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
# 리스트로 생성하기
data = [
    ['1000', 'Steve', 90.72], 
    ['1001', 'James', 78.09], 
    ['1002', 'Doyeon', 98.43], 
    ['1003', 'Jane', 64.19], 
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14],
]
df = pd.DataFrame(data)
print(df)

      0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [14]:
df = pd.DataFrame(data, columns=['학번', '이름', '점수'])
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [15]:
# 딕셔너리로 생성하기
data = { '학번' : ['1000', '1001', '1002', '1003', '1004', '1005'],
'이름' : [ 'Steve', 'James', 'Doyeon', 'Jane', 'Pilwoong', 'Tony'],
         '점수': [90.72, 78.09, 98.43, 64.19, 81.30, 99.14]}

df = pd.DataFrame(data)
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [17]:
df.head(3)

학번      이름     점수
0  1000   Steve  90.72
1  1001   James  78.09
2  1002  Doyeon  98.43

In [18]:
df.tail(3)

학번        이름     점수
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14

In [19]:
df['학번']

0    1000
1    1001
2    1002
3    1003
4    1004
5    1005
Name: 학번, dtype: object

In [23]:
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

Mounted at /gdrive


In [25]:
fileDf = pd.read_csv('/gdrive/MyDrive/dataset/pima-indians-diabetes.csv')
print(fileDf)

     6  148  72  1
0    1   85  66  0
1    8  183  64  1
2    1   89  66  0
3    0  137  40  1
4    5  116  74  0
..  ..  ...  .. ..
594  0  188  82  1
595  0   67  76  0
596  1   89  24  0
597  1  173  74  1
598  1  109  38  0

[599 rows x 4 columns]


In [28]:
print(fileDf.index)

RangeIndex(start=0, stop=599, step=1)


In [29]:
pip install numpy

In [30]:
import numpy as np
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [34]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
print(b.ndim) # n 차원
print(b.shape) # 크기

2
(2, 3)


In [38]:
print(a.ndim)
print(a.shape)

1
(5,)
